package ru.redstonemaster.web.config;

import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;

class UserNotificationTypeMigrationTest {

	@Test
	void userMuteValueCanBeStoredAfterEnumMigration() throws Exception {
		try (Connection connection = DriverManager.getConnection("jdbc:h2:mem:notification-type-migration", "sa", "")) {
			try (Statement statement = connection.createStatement()) {
				statement.execute("""
						CREATE TABLE user_notifications (
							id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							user_id BIGINT NOT NULL,
							type ENUM('NEWS', 'AVATAR_SETUP', 'LESSON_MODERATION') NOT NULL,
							source_key VARCHAR(64) NOT NULL,
							title_ru VARCHAR(255) NOT NULL,
							title_en VARCHAR(255) NOT NULL,
							message_ru VARCHAR(1024) NOT NULL,
							message_en VARCHAR(1024) NOT NULL,
							action_path VARCHAR(255) NOT NULL,
							action_label_ru VARCHAR(64) NOT NULL,
							action_label_en VARCHAR(64) NOT NULL,
							read BOOLEAN NOT NULL,
							read_at TIMESTAMP,
							created_at TIMESTAMP NOT NULL
						)
						""");
			}

			try (Statement statement = connection.createStatement()) {
				assertEquals(1, statement.executeUpdate(
						"INSERT INTO user_notifications (user_id, type, source_key, title_ru, title_en, message_ru, message_en, action_path, action_label_ru, action_label_en, read, created_at) "
								+ "VALUES (1, 'NEWS', 'news:1', 't', 't', 'm', 'm', '/news/1', 'Open', 'Open', FALSE, CURRENT_TIMESTAMP)"
				));
			}

			try (Statement statement = connection.createStatement()) {
				statement.execute("ALTER TABLE user_notifications ALTER COLUMN type VARCHAR(32) NOT NULL");
			}

			try (PreparedStatement statement = connection.prepareStatement("""
					INSERT INTO user_notifications (
						user_id, type, source_key, title_ru, title_en, message_ru, message_en,
						action_path, action_label_ru, action_label_en, read, created_at
					) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
					""")) {
				statement.setLong(1, 1L);
				statement.setString(2, "USER_MUTE");
				statement.setString(3, "user-mute:1:test");
				statement.setString(4, "Ограничение комментариев");
				statement.setString(5, "Comment restriction");
				statement.setString(6, "Тест");
				statement.setString(7, "Test");
				statement.setString(8, "/notifications");
				statement.setString(9, "Открыть");
				statement.setString(10, "Open");
				statement.setBoolean(11, false);
				assertEquals(1, statement.executeUpdate());
			}

			try (Statement statement = connection.createStatement();
				 ResultSet resultSet = statement.executeQuery(
						 "SELECT COUNT(*) FROM user_notifications WHERE type = 'USER_MUTE'"
				 )) {
				resultSet.next();
				assertEquals(1, resultSet.getInt(1));
			}
		}
	}
}
